# Generated by Django 5.1.3 on 2024-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="up_dated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="up_dated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="up_dated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("user", "article"), name="UIX_user_id_article_id"),
        ),
    ]
