# Generated by Django 5.1.3 on 2024-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0002_alter_article_up_dated_alter_like_up_dated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
